services:
  auto-grader:
    build: .
    container_name: urfu_teampro_auto_grader
    restart: unless-stopped
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    environment:
      - STUDENT_SCORE=100
      - CURATOR_SCORE=100
      - PYTHONUNBUFFERED=1  # чтоб лог сразу шел в консоль